# Generated by Django 2.2 on 2019-05-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_data',
            fields=[
                ('wd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('wd_humidity', models.CharField(max_length=10)),
                ('wd_temp', models.CharField(max_length=10)),
                ('wd_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
