# Generated by Django 2.2 on 2019-05-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='wd_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
